name: Build Lumi Installer

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: python build.py

      - name: Get version from config
        id: get_version
        shell: bash
        run: |
          VERSION=$(jq -r .version installer_config.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Rename artifact
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            mv dist/LumiInstaller.exe dist/LumiInstaller-Windows.exe
          else
            mv dist/LumiInstaller dist/LumiInstaller-Linux
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LumiInstaller-${{ matrix.os }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.build.outputs.VERSION }}
          name: v${{ needs.build.outputs.VERSION }}
          body: |
            Release built from commit: ${{ github.sha }}

            Changes:
            ${{ github.event.head_commit.message }}
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
